trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'eduardob-self-hosted'
    steps:
    - task: Docker@2
      displayName: Build and push docker image
      inputs:
        command: buildAndPush
        repository: eduardobiten/eduardob-experimental
        tags: latest
        dockerfile: Dockerfile

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: 'eduardob-self-hosted'
    steps:
    - task: SSH@0
      displayName: Run image on VM
      inputs:
        sshEndpoint: my-vm-connection
        runOptions: inline
        inline: |
          sudo docker stop my-app
          sudo docker rm my-app
          sudo docker pull eduardobiten/eduardob-experimental:latest
          sudo docker run -d -n my-app eduardobiten/eduardob-experimental:latest